<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_improving patient outcomes and liberati_c3ecb3</name>
   <tag></tag>
   <elementGuidId>5464d927-a37b-4cef-a49b-14cc04c5642a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-1396']/div/div[3]/div/div[3]/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.wp-image-4166</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f85d5c92-86e4-4618-84cf-a2706bb3a9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1efb32df-b102-4fcd-82d0-f1f744bd25fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>4167</value>
      <webElementGuid>a9ca7f19-be6f-46fc-9252-2aeacd9c04fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>4167</value>
      <webElementGuid>f6cc00db-3526-41e6-9a7c-df141d1cff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kinseed.com/wp-content/uploads/Element-Logo-MediLog.png</value>
      <webElementGuid>d6a25c44-79c8-401a-a1b1-aba2e09a703e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive wp-image-4166</value>
      <webElementGuid>afecf39b-ea7f-4397-a3a9-49d6ca9d7f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kinseed.com/wp-content/uploads/Element-Logo-MediLog-200x200.png 200w, https://kinseed.com/wp-content/uploads/Element-Logo-MediLog-400x400.png 400w, https://kinseed.com/wp-content/uploads/Element-Logo-MediLog-600x600.png 600w, https://kinseed.com/wp-content/uploads/Element-Logo-MediLog-800x800.png 800w, https://kinseed.com/wp-content/uploads/Element-Logo-MediLog-1200x1200.png 1200w, https://kinseed.com/wp-content/uploads/Element-Logo-MediLog.png 4167w</value>
      <webElementGuid>e5f775cc-9e9e-4733-a56c-ecafd318c7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, (max-width: 640px) 100vw, 200px</value>
      <webElementGuid>aab0f487-ce77-48bd-94e4-ddd0ba4b2dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1396&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;fusion-fullwidth fullwidth-box fusion-builder-row-4 fusion-flex-container has-pattern-background has-mask-background nonhundred-percent-fullwidth non-hundred-percent-height-scrolling&quot;]/div[@class=&quot;fusion-builder-row fusion-row fusion-flex-align-items-flex-start fusion-flex-content-wrap&quot;]/div[@class=&quot;fusion-layout-column fusion_builder_column fusion-builder-column-9 fusion_builder_column_1_5 1_5 fusion-flex-column fusion-animated&quot;]/div[@class=&quot;fusion-column-wrapper fusion-column-has-shadow fusion-flex-justify-content-flex-start fusion-content-layout-column&quot;]/div[@class=&quot;fusion-image-element&quot;]/div[@class=&quot;awb-image-frame awb-image-frame-3 imageframe-liftup imageframe-3&quot;]/span[@class=&quot;fusion-imageframe imageframe-none imageframe-3&quot;]/a[@class=&quot;fusion-no-lightbox&quot;]/img[@class=&quot;img-responsive wp-image-4166&quot;]</value>
      <webElementGuid>5dd6fed0-d39c-47a9-b40e-d34dccec53f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-1396']/div/div[3]/div/div[3]/div/div/div/span</value>
      <webElementGuid>dd3ca308-34da-441a-8876-ee269a1da56c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
