<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact</name>
   <tag></tag>
   <elementGuidId>3e2bd9ac-a962-42e6-9bc1-fda55eac7162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1392 > a.awb-menu__main-a.awb-menu__main-a_regular > span.menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1392']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c5dbfac-1b1d-4a20-af5f-abe0c8aa234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>389143eb-d6a9-46af-b078-013ebba4b1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>aa6e12bf-6cb4-4fe7-92d3-1bb0975d1615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1392&quot;)/a[@class=&quot;awb-menu__main-a awb-menu__main-a_regular&quot;]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>c0b45584-aa0c-41b1-8948-3f4ccea96057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1392']/a/span</value>
      <webElementGuid>e395604e-f2ab-43d9-8a0a-5b5b911dde05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Fact Sheets'])[1]/following::span[3]</value>
      <webElementGuid>a1fe5f8a-4fb4-4a0b-909e-05274b3203ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/following::span[4]</value>
      <webElementGuid>78a61c09-762a-48bf-a1b1-c18402ab55da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='connecting'])[1]/preceding::span[1]</value>
      <webElementGuid>6c449825-ab23-40a4-a655-c965ef12b36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='the disconnected'])[1]/preceding::span[1]</value>
      <webElementGuid>12f654ca-7694-40cd-a182-72f414c3f7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact']/parent::*</value>
      <webElementGuid>ccf538b0-bbdf-46ee-9de1-b96351274217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>45f1f1c8-2c05-4ed5-b1d7-7da72b4106f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>40b493ff-e574-4cbb-83f3-f31588bf65e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[1]</value>
      <webElementGuid>f483779b-59a7-44aa-ac91-909c6c9ae10c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
