<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MediTrack</name>
   <tag></tag>
   <elementGuidId>42514622-ee3f-4f74-ac31-1b2d12720a4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4240']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4240 > a.awb-menu__sub-a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3a194ad-a2e5-4c63-be91-1b3d815eaab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MediTrack</value>
      <webElementGuid>862ccc19-02e4-4c97-9ab3-0e67f252ec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4240&quot;)/a[@class=&quot;awb-menu__sub-a&quot;]/span[1]</value>
      <webElementGuid>5a256f85-516a-442d-b02d-bca7c068da8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4240']/a/span</value>
      <webElementGuid>6a6ad117-04c1-42ac-96c9-23a31ff87937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediConnect'])[1]/following::span[1]</value>
      <webElementGuid>7a2dfed3-c657-4915-b99a-14d93cc33c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediVue'])[1]/following::span[3]</value>
      <webElementGuid>16787fb1-427b-458b-a2a0-3a742eacfc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediWork'])[1]/preceding::span[2]</value>
      <webElementGuid>d98ba585-e2f8-48ee-87a7-aa855ba6a088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Partner'])[1]/preceding::span[6]</value>
      <webElementGuid>407249c9-ab90-44d2-9f3d-b340f87422f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MediTrack']/parent::*</value>
      <webElementGuid>9eb6b0fe-b461-4a98-b24b-4fbf4e345e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a/span</value>
      <webElementGuid>022a0d37-c557-4422-acc8-4dfbefa2b7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MediTrack' or . = 'MediTrack')]</value>
      <webElementGuid>80b491fd-04d7-49c2-9a41-fd38e8388c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
