<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MediLog</name>
   <tag></tag>
   <elementGuidId>5b86a55d-7403-4280-a342-a8502e1cf435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1322']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.awb-menu__sub-a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>881e0f6e-111e-4e64-8305-9c9626ec1dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MediLog</value>
      <webElementGuid>3a5b5546-7045-47ae-81ce-e107c248600e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1322&quot;)/a[@class=&quot;awb-menu__sub-a&quot;]/span[1]</value>
      <webElementGuid>4028bb5d-9ba4-42ee-9463-6af765d44db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1322']/a/span</value>
      <webElementGuid>5ce87ad2-aad2-4f9c-b2c4-4621e6ec9ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SwiftCare'])[1]/following::span[2]</value>
      <webElementGuid>3fbc7e20-15ba-4f57-a021-6fdf03f60924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to...'])[1]/following::span[9]</value>
      <webElementGuid>53ab932f-623f-455d-8c2e-9c30b56fe621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediVue'])[1]/preceding::span[2]</value>
      <webElementGuid>6a931038-0561-45b3-b299-7d059a8416ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediConnect'])[1]/preceding::span[4]</value>
      <webElementGuid>1c298f97-6ddb-4a8f-abc4-43a635e30e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MediLog']/parent::*</value>
      <webElementGuid>29648dba-05fc-4de0-b5c5-f56bee6445f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a/span</value>
      <webElementGuid>596807d2-edff-4306-bae2-88b6f0ccab20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MediLog' or . = 'MediLog')]</value>
      <webElementGuid>38fa0ae1-9ec5-4fbb-96ed-05503f23c9d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
