<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Testimonials</name>
   <tag></tag>
   <elementGuidId>63cc2ba7-7019-424d-b816-c2d0948ca94d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4156 > a.awb-menu__sub-a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4156']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0a7844c-be76-4d22-a1a5-ad9ea35884fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testimonials</value>
      <webElementGuid>fa18a121-aa55-4fb8-80a6-27d0792b0b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4156&quot;)/a[@class=&quot;awb-menu__sub-a&quot;]/span[1]</value>
      <webElementGuid>65f1e577-9307-47a5-93c2-e2778c107275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4156']/a/span</value>
      <webElementGuid>22424a22-8d12-4c7e-8536-c3141b965210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kinseed 10th Anniversary'])[1]/following::span[1]</value>
      <webElementGuid>a1ff7b41-0c00-4236-88d9-ed3a0f16df06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insights'])[1]/following::span[3]</value>
      <webElementGuid>aa5459a1-526d-4e2b-8e3e-5ac87f297feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest News'])[1]/preceding::span[1]</value>
      <webElementGuid>7f34dc83-b692-4da7-b611-8a89ae8f5008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/preceding::span[2]</value>
      <webElementGuid>35f8b400-334a-4a2d-945b-d8aa388eb0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testimonials']/parent::*</value>
      <webElementGuid>39c91d2b-e4fa-4cf6-a1b0-122d98e26033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a/span</value>
      <webElementGuid>b12e92e4-e2cb-4d03-af89-4d3114deedf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Testimonials' or . = 'Testimonials')]</value>
      <webElementGuid>768bf761-dcc6-4ab8-ab28-0ee0784a12f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
