<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insights</name>
   <tag></tag>
   <elementGuidId>4a458b8a-b412-423c-ac7a-1f64fdcd4f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4176 > a.awb-menu__main-a.awb-menu__main-a_regular > span.menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4176']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31cd4b08-523d-4a8e-8993-072a1ae93cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>b1aef711-ae7e-458a-a51d-bf152aa81237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insights</value>
      <webElementGuid>6d2e62d8-86d2-48ba-a48d-5f51be3c6a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4176&quot;)/a[@class=&quot;awb-menu__main-a awb-menu__main-a_regular&quot;]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>541826b7-e5d9-4246-a5c9-27f4f1469dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4176']/a/span</value>
      <webElementGuid>cc7f2452-d01d-4744-995f-38900bfc4bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Partner'])[1]/following::span[3]</value>
      <webElementGuid>b17bf523-e735-4fc5-b597-c6aea875dd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MediWork'])[1]/following::span[6]</value>
      <webElementGuid>0be745e4-788f-45ca-80b6-8abe5cbd86ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kinseed 10th Anniversary'])[1]/preceding::span[2]</value>
      <webElementGuid>397d8216-ede7-4b63-b9c0-6c9e8eba987f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimonials'])[1]/preceding::span[3]</value>
      <webElementGuid>a1207400-74a8-4bcc-b03b-21877022f314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Insights']/parent::*</value>
      <webElementGuid>31ec5445-e719-47a2-93c5-bc94582985ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>975a28c7-a6db-42b3-b3ae-8d74cc2ad7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Insights' or . = 'Insights')]</value>
      <webElementGuid>5d6f3783-7665-4873-a40f-f2bc8ffd9e94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
